parameters:
  wordpress.driver.wpcli.class: PaulGibbs\WordpressBehatExtension\Driver\WpcliDriver

services:
  wordpress.driver.wpcli:
    class: %wordpress.driver.wpcli.class%
    arguments:
      - %wordpress.driver.wpcli.alias%
      - %wordpress.path%
      - %mink.base_url%
      - %wordpress.driver.wpcli.binary%
    tags:
      - { name: wordpress.driver, alias: wpcli }
